import type { ActivityRow, Person } from "./data-context";

export const SAMPLE_ROSTER: Person[] = [
  {
    "Title Code": "D001",
    "Full Name": "Renata Okafor",
    Email: "renata.okafor@example.com",
    Phone: "212-555-0101",
    Department: "Field Sales",
    Region: "Manhattan, Bronx, Brooklyn, Queens, Staten Island, Nassau, Suffolk",
    Level: "Director",
  },
  {
    "Title Code": "M100",
    "Full Name": "Desmond Iyer",
    Email: "desmond.iyer@example.com",
    Phone: "212-555-0110",
    "Reports To": "D001",
    Department: "Field Sales",
    Region: "Manhattan",
    Level: "Manager",
  },
  {
    "Title Code": "M200",
    "Full Name": "Priya Raghunathan",
    Email: "priya.r@example.com",
    Phone: "718-555-0120",
    "Reports To": "D001",
    Department: "Field Sales",
    Region: "Bronx",
    Level: "Manager",
  },
  {
    "Title Code": "M300",
    "Full Name": "Tobias Lund",
    Email: "tobias.lund@example.com",
    Phone: "718-555-0130",
    "Reports To": "D001",
    Department: "Field Sales",
    Region: "Brooklyn",
    Level: "Manager",
  },
  {
    "Title Code": "M400",
    "Full Name": "Grace Alvarado",
    Email: "grace.alvarado@example.com",
    Phone: "718-555-0140",
    "Reports To": "D001",
    Department: "Field Sales",
    Region: "Queens",
    Level: "Manager",
  },
  {
    "Title Code": "M500",
    "Full Name": "Owen Petrosyan",
    Email: "owen.p@example.com",
    Phone: "718-555-0150",
    "Reports To": "D001",
    Department: "Field Sales",
    Region: "Staten Island",
    Level: "Manager",
  },
  {
    "Title Code": "M600",
    "Full Name": "Nadia Cheung",
    Email: "nadia.cheung@example.com",
    Phone: "516-555-0160",
    "Reports To": "D001",
    Department: "Field Sales",
    Region: "Nassau",
    Level: "Manager",
  },
  {
    "Title Code": "M700",
    "Full Name": "Aaron Whitfield",
    Email: "aaron.w@example.com",
    Phone: "631-555-0170",
    "Reports To": "D001",
    Department: "Field Sales",
    Region: "Suffolk",
    Level: "Manager",
  },
  {
    "Title Code": "S101",
    "Full Name": "Mateo Bianchi",
    Email: "mateo.bianchi@example.com",
    Phone: "212-555-0201",
    "Reports To": "M100",
    Department: "Field Sales",
    Region: "Manhattan",
    Level: "Rep",
  },
  {
    "Title Code": "S102",
    "Full Name": "June Park",
    Email: "june.park@example.com",
    Phone: "212-555-0202",
    "Reports To": "M100",
    Department: "Field Sales",
    Region: "Manhattan",
    Level: "Rep",
  },
  {
    "Title Code": "S201",
    "Full Name": "Kofi Mensah",
    Email: "kofi.mensah@example.com",
    Phone: "718-555-0203",
    "Reports To": "M200",
    Department: "Field Sales",
    Region: "Bronx",
    Level: "Rep",
  },
  {
    "Title Code": "S301",
    "Full Name": "Leah Rosenberg",
    Email: "leah.r@example.com",
    Phone: "718-555-0204",
    "Reports To": "M300",
    Department: "Field Sales",
    Region: "Brooklyn",
    Level: "Rep",
  },
  {
    "Title Code": "S302",
    "Full Name": "Diego Salcedo",
    Email: "diego.salcedo@example.com",
    Phone: "718-555-0205",
    "Reports To": "M300",
    Department: "Field Sales",
    Region: "Brooklyn",
    Level: "Rep",
  },
  {
    "Title Code": "S401",
    "Full Name": "Hana Suzuki",
    Email: "hana.suzuki@example.com",
    Phone: "718-555-0206",
    "Reports To": "M400",
    Department: "Field Sales",
    Region: "Queens",
    Level: "Rep",
  },
  {
    "Title Code": "S501",
    "Full Name": "Colm Beckett",
    Email: "colm.beckett@example.com",
    Phone: "718-555-0207",
    "Reports To": "M500",
    Department: "Field Sales",
    Region: "Staten Island",
    Level: "Rep",
  },
  {
    "Title Code": "S601",
    "Full Name": "Yara Haddad",
    Email: "yara.haddad@example.com",
    Phone: "516-555-0208",
    "Reports To": "M600",
    Department: "Field Sales",
    Region: "Nassau",
    Level: "Rep",
  },
  {
    "Title Code": "S701",
    "Full Name": "Simon Adeyemi",
    Email: "simon.adeyemi@example.com",
    Phone: "631-555-0209",
    "Reports To": "M700",
    Department: "Field Sales",
    Region: "Suffolk",
    Level: "Rep",
  },
];

type SampleActivity = Omit<ActivityRow, "id">;

export const SAMPLE_ACTIVITY: SampleActivity[] = [
  {
    Status: "Scheduled",
    Title: "Quarterly display reset",
    RetailerId: "RT-4410",
    "Application Date": "2026-07-28",
    "Scheduled Date": "2026-08-14",
    Address: "88 Delancey St, New York, NY",
    Route: "101",
    Task: "Merchandising",
    Model: "Compact",
    Brand: "Northline",
    Area: "Lower East Side",
    Phone: "212-555-0301",
    Notes: "Ask for Yusuf at the counter.",
  },
  {
    Status: "Completed",
    Title: "New retailer onboarding",
    RetailerId: "RT-4411",
    "Application Date": "2026-07-20",
    "Scheduled Date": "2026-08-04",
    Address: "1200 Broadway, New York, NY",
    Route: "S101",
    Task: "Onboarding",
    Model: "Standard",
    Brand: "Northline",
    Area: "NoMad",
    Phone: "212-555-0302",
    Notes: "Signed. Fixtures delivered.",
  },
  {
    Status: "Refused",
    Title: "Planogram audit",
    RetailerId: "RT-4415",
    "Application Date": "2026-07-22",
    "Scheduled Date": "2026-08-06",
    Address: "455 W 43rd St, New York, NY",
    Route: "102",
    Task: "Audit",
    Model: "Compact",
    Brand: "Harbor",
    Area: "Hell's Kitchen",
    Phone: "212-555-0303",
    Notes: "Owner declined — revisit next cycle.",
  },
  {
    Status: "Scheduled",
    Title: "Shelf space negotiation",
    RetailerId: "RT-4502",
    "Application Date": "2026-08-01",
    "Scheduled Date": "2026-08-18",
    Address: "2400 Grand Concourse, Bronx, NY",
    Route: "201",
    Task: "Negotiation",
    Model: "Standard",
    Brand: "Northline",
    Area: "Fordham",
    Phone: "718-555-0304",
  },
  {
    Status: "Completed",
    Title: "Seasonal endcap install",
    RetailerId: "RT-4610",
    "Application Date": "2026-07-15",
    "Scheduled Date": "2026-08-01",
    Address: "770 Fulton St, Brooklyn, NY",
    Route: "301",
    Task: "Merchandising",
    Model: "Premium",
    Brand: "Harbor",
    Area: "Fort Greene",
    Phone: "718-555-0305",
    Notes: "Photos uploaded to shared drive.",
  },
  {
    Status: "Scheduled",
    Title: "Stock recovery visit",
    RetailerId: "RT-4611",
    "Application Date": "2026-08-02",
    "Scheduled Date": "2026-08-15",
    Address: "31 Bedford Ave, Brooklyn, NY",
    Route: "302",
    Task: "Restock",
    Model: "Compact",
    Brand: "Northline",
    Area: "Williamsburg",
    Phone: "718-555-0306",
  },
  {
    Status: "Scheduled",
    Title: "Damaged fixture replacement",
    RetailerId: "RT-4702",
    "Application Date": "2026-08-03",
    "Scheduled Date": "2026-08-19",
    Address: "37-11 Main St, Flushing, NY",
    Route: "401",
    Task: "Service",
    Model: "Standard",
    Brand: "Harbor",
    Area: "Flushing",
    Phone: "718-555-0307",
    Notes: "Bring the replacement bracket kit.",
  },
  {
    Status: "Completed",
    Title: "Contract renewal",
    RetailerId: "RT-4801",
    "Application Date": "2026-07-11",
    "Scheduled Date": "2026-07-30",
    Address: "1441 Forest Ave, Staten Island, NY",
    Route: "501",
    Task: "Renewal",
    Model: "Premium",
    Brand: "Northline",
    Area: "Port Richmond",
    Phone: "718-555-0308",
  },
  {
    Status: "Scheduled",
    Title: "First-time buyer walkthrough",
    RetailerId: "RT-4905",
    "Application Date": "2026-08-05",
    "Scheduled Date": "2026-08-20",
    Address: "300 Old Country Rd, Garden City, NY",
    Route: "601",
    Task: "Onboarding",
    Model: "Standard",
    Brand: "Harbor",
    Area: "Garden City",
    Phone: "516-555-0309",
  },
  {
    Status: "Scheduled",
    Title: "Route coverage backfill",
    RetailerId: "RT-5010",
    "Application Date": "2026-08-06",
    "Scheduled Date": "2026-08-21",
    Address: "1701 Sunrise Hwy, Bay Shore, NY",
    Route: "701",
    Task: "Coverage",
    Model: "Compact",
    Brand: "Northline",
    Area: "Bay Shore",
    Phone: "631-555-0310",
  },
  {
    Status: "Scheduled",
    Title: "Unassigned territory lead",
    RetailerId: "RT-5099",
    "Application Date": "2026-08-07",
    "Scheduled Date": "2026-08-22",
    Address: "18 Beach Rd, Montauk, NY",
    Route: "999",
    Task: "Prospecting",
    Model: "Standard",
    Brand: "Harbor",
    Area: "Montauk",
    Phone: "631-555-0311",
    Notes: "No rep assigned to this route yet.",
  },
];
